version: "3.8"
services:
  bot:
    build: .
    container_name: bot
    command: python -m bot
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASS
      POSTGRES_DB: POSTGRES_DB

volumes:
  db-data: